### PR TITLE
Initialize readme page

### PR DESCRIPTION
**Pull request by QuangLyHo**
Added a readme file for our repo

### CODE REVIEW

**Review by Medic1111 — APPROVED** [review]
Excellet

**Comment by terrifricker** [comment]
Love it!

Like medic said, we should be making our pull requests to the development branch.

@medic  I hadn't used a development branch before.  I did end up making my first pull request to development, but I have questions.

 I did the following (not including mistakes like misspelling development and forgetting to git add before git push, etc.)

`git switch development`
`git checkout -b add-index-boilerplate`
made changes to index.html
`git commit -m "add html index boilerplate"`
`git add index.html`
`git push origin add-index-boilerplate`
Then came to the repository to create a pull request.
I don't have a screen shot, but at the top of the pull request, it automatically asked to make the pull request to "main" and I had to choose "development".

Before pushing to origin, I tried this
`git push development add-index-boilerplate`
but got the error messages
`fatal: 'development' does not appear to be a git repository`
`fatal: Could not read from remote repository.`
so I just did `git push` to see what the message would be
and it said 
`git push --set-upstream origin add-index-boilerplate`

So questions,
1.  One of the articles referred to by chingu, said to switch to branch development before creating a new branch, so that the new branch was related to the development branch, but that is now how I understand how git works.
2. I'll research this, but is there a way to make our pull requests directly to development instead of main ( a change that I would make to the repository itself )?

**Comment by Medic1111** [comment]
> Love it!
> 
> Like medic said, we should be making our pull requests to the development branch.
> 
> @medic I hadn't used a development branch before. I did end up making my first pull request to development, but I have questions.
> 
> I did the following (not including mistakes like misspelling development and forgetting to git add before git push, etc.)
> 
> `git switch development` `git checkout -b add-index-boilerplate` made changes to index.html `git commit -m "add html index boilerplate"` `git add index.html` `git push origin add-index-boilerplate` Then came to the repository to create a pull request. I don't have a screen shot, but at the top of the pull request, it automatically asked to make the pull request to "main" and I had to choose "development".
> 
> Before pushing to origin, I tried this `git push development add-index-boilerplate` but got the error messages `fatal: 'development' does not appear to be a git repository` `fatal: Could not read from remote repository.` so I just did `git push` to see what the message would be and it said `git push --set-upstream origin add-index-boilerplate`
> 
> So questions,
> 
> 1. One of the articles referred to by chingu, said to switch to branch development before creating a new branch, so that the new branch was related to the development branch, but that is now how I understand how git works.
> 2. I'll research this, but is there a way to make our pull requests directly to development instead of main ( a change that I would make to the repository itself )?

GIT PUSH ORIGIN DEVELOPMENT
or any other name 
Try that and let me know

**Review by terrifricker — APPROVED** [review]

**Comment by terrifricker** [comment]
I approve, but let's wait until the merge conflict is resolved before actually merging this pull request.

**Review by Emimint — COMMENTED** [review]
Good to go!

**Comment by QuangLyHo** [comment]
> Excellent, But should it be a PR to DEVELOPMENT branch? =)

Ah okay. I didn't realize we had a development branch and will note that for future PR's

**Pull request merged**
